# Generated by Django 5.0.6 on 2024-07-02 09:32

import account.utility
import account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(default=account.utility.generate_account_number, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pin', models.CharField(max_length=4, validators=[account.validators.validate_pin])),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('account_type', models.CharField(choices=[('S', 'SAVINGS'), ('C', 'CURRENT'), ('D', 'DOM')], default='S', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEB', 'DEBIT'), ('CRE', 'CREDIT'), ('TRA', 'TRANSFER')], default='CRE', max_length=3)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_status', models.CharField(choices=[('S', 'SUCCESSFUL'), ('F', 'FAILED'), ('P', 'PENDING')], default='S', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.account')),
            ],
        ),
    ]
